version: '3.9'

services:
  lostandfound.authservice:
    container_name: auth-service
    build:
      context: .
      dockerfile: AuthService/src/LostAndFound.AuthService/Dockerfile
    ports:
        - "5100:443"

  lostandfound.chatservice:
    container_name: chat-service
    build:
      context: .
      dockerfile: ChatService/src/LostAndFound.ChatService/Dockerfile
    ports:
        - "5200:443"

  lostandfound.gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Gateway/src/LostAndFound.Gateway/Dockerfile
    ports:
        - "5000:443"
    depends_on:
        - "lostandfound.authservice"
        - "lostandfound.chatservice"
        - "lostandfound.profileservice"
        - "lostandfound.publicationservice"

  lostandfound.profileservice:
    container_name: profile-service
    build:
      context: .
      dockerfile: ProfileService/src/LostAndFound.ProfileService/Dockerfile
    ports:
        - "5300:443"

  lostandfound.publicationservice:
    container_name: publication-service
    build:
      context: .
      dockerfile: PublicationService/src/LostAndFound.PublicationService/Dockerfile
    ports:
        - "5400:443"
