version: '3.9'

x-common-variables: &common-variables
    ASPNETCORE_ENVIRONMENT: Production
    PositionStackService__AccessKey: "e3aab94387af95a665b8c6e15d2bee78"
    LostAndFoundAuthentication__AccessTokenSecret: "5JlMfZSG1qokOwJiangsnKYr8BfCmfRBh4lj5PtctKKNl6NCKQ7q_5oQFRoGF6WYVmQuKE8bIuhRrwbZksXjOBG48zIaa193HvffmSv1XXyfGYuZverFtbpINKGyg-l8tp8XDGUWw_UmhT6vyGq7lzH4FzoOZ-o284jTF2_5A-k"
    LostAndFoundAuthentication__RefreshTokenSecret: "1Dnm21C8yjIh_aBIRzl-hY97XfAGpF7Lo1rHhh92Uh5YT20InJxx-WxCwSPCtLa7RplhBG_FKRzMgsYiQWZ-wqFs7-aH-wDbu74QnPqUlJ1kfXJYiATPmx86KoJVLqIXo2gNDEunqdWFN87tgLfGVeaSYyIB9_SLc8OtzBvP9mM"

services:
  lostandfound.azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: lostandfound-azurite
    hostname: azurite
    restart: always
    command: 'azurite --loose --blobHost 0.0.0.0 --blobPort 10000 --location /workspace --debug /workspace/debug.log'
    ports:
        - 10100:10000
    volumes:
        - ./azurite-prod:/workspace

  lostandfound.rabbitmq:
    image: rabbitmq:3-management
    ports:
        - 5610:15672
        - 5600:5672
    container_name: lostandfound-rabbitmq
    
  lostandfound.mongodb:
    container_name: "lostandfound-mongodb"
    image: mongo:latest
    ports:
        - 5717:27017

  lostandfound.authservice:
    container_name: auth-service
    build:
      context: .
      dockerfile: AuthService/src/LostAndFound.AuthService/Dockerfile
    ports:
        - "6100:80"
    depends_on:
        - "lostandfound.mongodb"
        - "lostandfound.rabbitmq"
    environment:
        <<: *common-variables

  lostandfound.chatservice:
    container_name: chat-service
    build:
      context: .
      dockerfile: ChatService/src/LostAndFound.ChatService/Dockerfile
    ports:
        - "6200:80"
    depends_on:
        - "lostandfound.mongodb"
    environment:
        <<: *common-variables

  lostandfound.gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: Gateway/src/LostAndFound.Gateway/Dockerfile
    ports:
        - "6500:80"
    depends_on:
        - "lostandfound.authservice"
        - "lostandfound.chatservice"
        - "lostandfound.profileservice"
        - "lostandfound.publicationservice"
    environment:
        <<: *common-variables
        
  lostandfound.profileservice:
    container_name: profile-service
    build:
      context: .
      dockerfile: ProfileService/src/LostAndFound.ProfileService/Dockerfile
    ports:
        - "6300:80"
    restart: on-failure
    depends_on:        
        - "lostandfound.mongodb"
        - "lostandfound.azurite"
        - "lostandfound.rabbitmq"
    environment:
        <<: *common-variables

  lostandfound.publicationservice:
    container_name: publication-service
    build:
      context: .
      dockerfile: PublicationService/src/LostAndFound.PublicationService/Dockerfile
    ports:
        - "6400:80"
    depends_on:
        - "lostandfound.mongodb"
        - "lostandfound.azurite"
    environment:
        <<: *common-variables
