parameters:
  - name: nodeVersion
    type: string
    default: "16.x"

  - name: mobileProjectDirectory
    type: string

  - name: artifactName
    type: string

stages:
  - stage: BuildReactNativeApp
    displayName: Build ReactNativeApp
    jobs:
      - job: Build
        displayName: Build ReactNativeApp
        steps:
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: "${{ parameters.nodeVersion }}"

          - script: |
              npm ci
            displayName: "Run script: npm clean install"
            workingDirectory: ${{ parameters.mobileProjectDirectory }}

          - task: Gradle@2
            inputs:
              workingDirectory: '${{ parameters.mobileProjectDirectory }}/android'
              gradleWrapperFile: '${{ parameters.mobileProjectDirectory }}/android/gradlew'
              gradleOptions: '-Xmx3072m'
              publishJUnitResults: false
              testResultsFiles: '**/TEST-*.xml'
              tasks: 'assembleRelease'

          - task: AndroidSigning@2
            inputs:
              apkFiles: '**/*.apk'
              jarsign: true
              jarsignerKeystoreFile: 'android.keystore'
              jarsignerKeystorePassword: '$(AndroidKeyStorePassword)'
              jarsignerKeystoreAlias: '$(AndroidKeyAlias)'
              jarsignerKeyPassword: '$(AndroidKeyStorePassword)'
              zipalign: true

          - script: mv ${{ parameters.mobileProjectDirectory }}/android/app/build/outputs/apk/release/app-release-unsigned.apk ReactNativePipeline$(Build.BuildNumber).apk
            displayName: 'Rename apk'

          - task: PublishBuildArtifacts@1
            inputs:
              pathtoPublish: ReactNativePipeline$(Build.BuildNumber).apk
              artifactName: drop
              publishLocation: 'container'